rm(list=ls())
load("~/Desktop/ops.RData")

pdf("~/Desktop/MSReport/MSFigs/ops.pdf")
par(mfrow=c(3,3), mar=c(5,5,4,2)+0.1)
hist(op1$latency_ms, xlab="Latency (ms)", ylab="Count", main="op1", col="turquoise", xlim=c(0,quantile(op1$latency_ms,0.97)), breaks=1000)
hist(op2$latency_ms, xlab="Latency (ms)", ylab="Count", main="op2", col="turquoise", xlim=c(0,quantile(op2$latency_ms,0.95)), breaks=250)
hist(op3$latency_ms, xlab="Latency (ms)", ylab="Count", main="op3", col="turquoise", xlim=c(0,quantile(op3$latency_ms,0.99)), breaks=100)
hist(op4$latency_ms, xlab="Latency (ms)", ylab="Count", main="op4", col="turquoise", xlim=c(0,quantile(op4$latency_ms,0.99)), breaks=200)
hist(op5$latency_ms, xlab="Latency (ms)", ylab="Count", main="op5", col="turquoise", xlim=c(0,quantile(op5$latency_ms,0.99)), breaks=50)
hist(op6$latency_ms, xlab="Latency (ms)", ylab="Count", main="op6", col="turquoise", xlim=c(0,quantile(op6$latency_ms,0.99)), breaks=1000)
hist(op7$latency_ms, xlab="Latency (ms)", ylab="Count", main="op7", col="turquoise", xlim=c(0,quantile(op7$latency_ms,0.985)), breaks=1000)
hist(op8$latency_ms, xlab="Latency (ms)", ylab="Count", main="op8", col="turquoise", xlim=c(0,quantile(op8$latency_ms,0.99)), breaks=2000)
hist(op9$latency_ms, xlab="Latency (ms)", ylab="Count", main="op9", col="turquoise", xlim=c(0,quantile(op9$latency_ms,0.999)), breaks=2000)
dev.off()